"""Add title and featured_image columns

Revision ID: 6baad84874d0
Revises: 8f89611c005d
Create Date: 2022-03-13 22:12:36.712386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6baad84874d0'
down_revision = '8f89611c005d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('posts', sa.Column('featured_img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'featured_img')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
